- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep sampleapp | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep sampleapp`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep sampleapp  | awk '{print $1}' | wc -l` -gt 0 ]; then
            echo "app service found, No actions taken"
            #kubectl delete svc `kubectl get svc | grep sampleapp | awk '{print $1}'`
         else
            echo "No app service found it will be created"
         fi
    - name: deploy app
      shell: kubectl create deployment sampleapp --image=lerndevops/samplejavaapp:{{ build }}
    - name: increase replicas 
      shell: kubectl scale deploy sampleapp --replicas=2
    - name: deploy service
      shell: kubectl expose deployment sampleapp --name sampleapp --type NodePort --port 80 --target-port 8080
