kind: Deployment
apiVersion: apps/v1
metadata:
  name: addressbook
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: samplejavaapp
    spec:
      containers:
      - name: samplejavaapp
        image: lerndevops/samplejavaapp:bno
        ports:
        - name: http
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: addressbook
spec:
  type: NodePort
  selector:
    app: sampleapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
